export const ANIME_LIST_URL = "http://localhost:8000/anime/animelist/"
export const GENRES_URL = "http://localhost:8000/anime/genres/"
export const YEARS_URL = "http://localhost:8000/anime/years/"
export const BASE_URL = "http://localhost:8000"
export const ANIME_DETAIL_URL = "http://localhost:8000/anime/anime-detail/"
export const EPISODE_URL = "http://localhost:8000/anime/episode/"
export const FILTER_URL = "http://localhost:8000/anime/filter/"
export const SEARCH_URL = "http://localhost:8000/anime/search/"